env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - '@nuxtjs/eslint-config-typescript'
  - 'plugin:vue/essential'
  - 'plugin:vue/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - "plugin:prettier/recommended"
  - 'prettier'
  - 'prettier/vue'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
  - 'prettier'
rules:
  no-unused-vars: 0
  no-case-declarations: 0
